#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : bpftrace
Version  : 0.9.2
Release  : 3
URL      : https://github.com/iovisor/bpftrace/archive/v0.9.2.tar.gz
Source0  : https://github.com/iovisor/bpftrace/archive/v0.9.2.tar.gz
Source1  : https://github.com/google/googletest/archive/release-1.8.1.tar.gz
Summary  : High-level tracing language for Linux eBPF
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause
Requires: bpftrace-bin = %{version}-%{release}
Requires: bpftrace-data = %{version}-%{release}
Requires: bpftrace-license = %{version}-%{release}
Requires: bpftrace-man = %{version}-%{release}
BuildRequires : bcc-dev
BuildRequires : bison-dev
BuildRequires : buildreq-cmake
BuildRequires : flex
BuildRequires : flex-dev
BuildRequires : glibc-dev
BuildRequires : llvm-dev
BuildRequires : llvm-extras
BuildRequires : pkgconfig(libelf)
BuildRequires : python3

%description
The Google Mock class generator is an application that is part of cppclean.
For more information about cppclean, visit http://code.google.com/p/cppclean/

%package bin
Summary: bin components for the bpftrace package.
Group: Binaries
Requires: bpftrace-data = %{version}-%{release}
Requires: bpftrace-license = %{version}-%{release}

%description bin
bin components for the bpftrace package.


%package data
Summary: data components for the bpftrace package.
Group: Data

%description data
data components for the bpftrace package.


%package license
Summary: license components for the bpftrace package.
Group: Default

%description license
license components for the bpftrace package.


%package man
Summary: man components for the bpftrace package.
Group: Default

%description man
man components for the bpftrace package.


%prep
%setup -q -n bpftrace-0.9.2
cd ..
%setup -q -T -D -n bpftrace-0.9.2 -b 1
mkdir -p 3rdparty/gtest
cp -r %{_topdir}/BUILD/googletest-release-1.8.1/* %{_topdir}/BUILD/bpftrace-0.9.2/3rdparty/gtest

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1565989251
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%cmake .. -DBUILD_TESTING=OFF
make  %{?_smp_mflags} VERBOSE=1
popd

%install
export SOURCE_DATE_EPOCH=1565989251
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/bpftrace
cp 3rdparty/gtest/LICENSE %{buildroot}/usr/share/package-licenses/bpftrace/3rdparty_gtest_LICENSE
cp 3rdparty/gtest/googlemock/LICENSE %{buildroot}/usr/share/package-licenses/bpftrace/3rdparty_gtest_googlemock_LICENSE
cp 3rdparty/gtest/googlemock/scripts/generator/LICENSE %{buildroot}/usr/share/package-licenses/bpftrace/3rdparty_gtest_googlemock_scripts_generator_LICENSE
cp 3rdparty/gtest/googletest/LICENSE %{buildroot}/usr/share/package-licenses/bpftrace/3rdparty_gtest_googletest_LICENSE
cp LICENSE %{buildroot}/usr/share/package-licenses/bpftrace/LICENSE
pushd clr-build
%make_install
popd
## install_append content
mkdir -p %{buildroot}/usr/share
mv %{buildroot}/usr/man %{buildroot}/usr/share
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/bpftrace

%files data
%defattr(-,root,root,-)
/usr/share/bpftrace/tools/bashreadline.bt
/usr/share/bpftrace/tools/biolatency.bt
/usr/share/bpftrace/tools/biosnoop.bt
/usr/share/bpftrace/tools/bitesize.bt
/usr/share/bpftrace/tools/capable.bt
/usr/share/bpftrace/tools/cpuwalk.bt
/usr/share/bpftrace/tools/dcsnoop.bt
/usr/share/bpftrace/tools/doc/bashreadline_example.txt
/usr/share/bpftrace/tools/doc/biolatency_example.txt
/usr/share/bpftrace/tools/doc/biosnoop_example.txt
/usr/share/bpftrace/tools/doc/bitesize_example.txt
/usr/share/bpftrace/tools/doc/capable_example.txt
/usr/share/bpftrace/tools/doc/cpuwalk_example.txt
/usr/share/bpftrace/tools/doc/dcsnoop_example.txt
/usr/share/bpftrace/tools/doc/execsnoop_example.txt
/usr/share/bpftrace/tools/doc/gethostlatency_example.txt
/usr/share/bpftrace/tools/doc/killsnoop_example.txt
/usr/share/bpftrace/tools/doc/loads_example.txt
/usr/share/bpftrace/tools/doc/mdflush_example.txt
/usr/share/bpftrace/tools/doc/oomkill_example.txt
/usr/share/bpftrace/tools/doc/opensnoop_example.txt
/usr/share/bpftrace/tools/doc/pidpersec_example.txt
/usr/share/bpftrace/tools/doc/runqlat_example.txt
/usr/share/bpftrace/tools/doc/runqlen_example.txt
/usr/share/bpftrace/tools/doc/statsnoop_example.txt
/usr/share/bpftrace/tools/doc/syncsnoop_example.txt
/usr/share/bpftrace/tools/doc/syscount_example.txt
/usr/share/bpftrace/tools/doc/tcpaccept_example.txt
/usr/share/bpftrace/tools/doc/tcpconnect_example.txt
/usr/share/bpftrace/tools/doc/tcpdrop_example.txt
/usr/share/bpftrace/tools/doc/tcpretrans_example.txt
/usr/share/bpftrace/tools/doc/vfscount_example.txt
/usr/share/bpftrace/tools/doc/vfsstat_example.txt
/usr/share/bpftrace/tools/doc/writeback_example.txt
/usr/share/bpftrace/tools/doc/xfsdist_example.txt
/usr/share/bpftrace/tools/execsnoop.bt
/usr/share/bpftrace/tools/gethostlatency.bt
/usr/share/bpftrace/tools/killsnoop.bt
/usr/share/bpftrace/tools/loads.bt
/usr/share/bpftrace/tools/mdflush.bt
/usr/share/bpftrace/tools/oomkill.bt
/usr/share/bpftrace/tools/opensnoop.bt
/usr/share/bpftrace/tools/pidpersec.bt
/usr/share/bpftrace/tools/runqlat.bt
/usr/share/bpftrace/tools/runqlen.bt
/usr/share/bpftrace/tools/statsnoop.bt
/usr/share/bpftrace/tools/syncsnoop.bt
/usr/share/bpftrace/tools/syscount.bt
/usr/share/bpftrace/tools/tcpaccept.bt
/usr/share/bpftrace/tools/tcpconnect.bt
/usr/share/bpftrace/tools/tcpdrop.bt
/usr/share/bpftrace/tools/tcpretrans.bt
/usr/share/bpftrace/tools/vfscount.bt
/usr/share/bpftrace/tools/vfsstat.bt
/usr/share/bpftrace/tools/writeback.bt
/usr/share/bpftrace/tools/xfsdist.bt

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/bpftrace/3rdparty_gtest_LICENSE
/usr/share/package-licenses/bpftrace/3rdparty_gtest_googlemock_LICENSE
/usr/share/package-licenses/bpftrace/3rdparty_gtest_googlemock_scripts_generator_LICENSE
/usr/share/package-licenses/bpftrace/3rdparty_gtest_googletest_LICENSE
/usr/share/package-licenses/bpftrace/LICENSE

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man8/bashreadline.8.gz
/usr/share/man/man8/biolatency.8.gz
/usr/share/man/man8/biosnoop.8.gz
/usr/share/man/man8/bitesize.8.gz
/usr/share/man/man8/bpftrace.8.gz
/usr/share/man/man8/capable.8.gz
/usr/share/man/man8/cpuwalk.8.gz
/usr/share/man/man8/dcsnoop.8.gz
/usr/share/man/man8/execsnoop.8.gz
/usr/share/man/man8/gethostlatency.8.gz
/usr/share/man/man8/killsnoop.8.gz
/usr/share/man/man8/loads.8.gz
/usr/share/man/man8/mdflush.8.gz
/usr/share/man/man8/oomkill.8.gz
/usr/share/man/man8/opensnoop.8.gz
/usr/share/man/man8/pidpersec.8.gz
/usr/share/man/man8/runqlat.8.gz
/usr/share/man/man8/runqlen.8.gz
/usr/share/man/man8/statsnoop.8.gz
/usr/share/man/man8/syncsnoop.8.gz
/usr/share/man/man8/syscount.8.gz
/usr/share/man/man8/tcpaccept.8.gz
/usr/share/man/man8/tcpconnect.8.gz
/usr/share/man/man8/tcpdrop.8.gz
/usr/share/man/man8/tcpretrans.8.gz
/usr/share/man/man8/vfscount.8.gz
/usr/share/man/man8/vfsstat.8.gz
/usr/share/man/man8/writeback.8.gz
/usr/share/man/man8/xfsdist.8.gz
