#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : bpftrace
Version  : 51500dfbe2529823a261af2ab2879d3fb7cd8bf9
Release  : 1
URL      : https://github.com/iovisor/bpftrace/archive/51500dfbe2529823a261af2ab2879d3fb7cd8bf9.tar.gz
Source0  : https://github.com/iovisor/bpftrace/archive/51500dfbe2529823a261af2ab2879d3fb7cd8bf9.tar.gz
Source1  : https://github.com/google/googletest/archive/release-1.8.1.tar.gz
Source2  : https://github.com/iovisor/bcc/archive/v0.7.0.tar.gz
Summary  : BPF Compiler Collection (BCC)
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause
Requires: bpftrace-bin = %{version}-%{release}
Requires: bpftrace-data = %{version}-%{release}
Requires: bpftrace-license = %{version}-%{release}
BuildRequires : bison-dev
BuildRequires : buildreq-cmake
BuildRequires : flex
BuildRequires : flex-dev
BuildRequires : git
BuildRequires : glibc-dev
BuildRequires : llvm-dev
BuildRequires : llvm-extras
BuildRequires : pkgconfig(libelf)
BuildRequires : python3
Patch1: 0001-Do-not-force-downloading-ExternalProjects.patch
Patch2: 0002-Fix-missing-include-ftw.h.patch

%description
Python bindings for BPF Compiler Collection (BCC). Control a BPF program from
userspace.

%package bin
Summary: bin components for the bpftrace package.
Group: Binaries
Requires: bpftrace-data = %{version}-%{release}
Requires: bpftrace-license = %{version}-%{release}

%description bin
bin components for the bpftrace package.


%package data
Summary: data components for the bpftrace package.
Group: Data

%description data
data components for the bpftrace package.


%package license
Summary: license components for the bpftrace package.
Group: Default

%description license
license components for the bpftrace package.


%prep
%setup -q -n bpftrace-51500dfbe2529823a261af2ab2879d3fb7cd8bf9
cd ..
%setup -q -T -D -n bpftrace-51500dfbe2529823a261af2ab2879d3fb7cd8bf9 -b 2
cd ..
%setup -q -T -D -n bpftrace-51500dfbe2529823a261af2ab2879d3fb7cd8bf9 -b 1
mkdir -p 3rdparty/bcc
mv %{_topdir}/BUILD/bcc-0.7.0/* %{_topdir}/BUILD/bpftrace-51500dfbe2529823a261af2ab2879d3fb7cd8bf9/3rdparty/bcc
mkdir -p 3rdparty/gtest
mv %{_topdir}/BUILD/googletest-release-1.8.1/* %{_topdir}/BUILD/bpftrace-51500dfbe2529823a261af2ab2879d3fb7cd8bf9/3rdparty/gtest
%patch1 -p1
%patch2 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1539668458
mkdir -p clr-build
pushd clr-build
%cmake .. -DOFFLINE_BUILDS=1
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1539668458
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/bpftrace
cp 3rdparty/bcc/LICENSE.txt %{buildroot}/usr/share/package-licenses/bpftrace/3rdparty_bcc_LICENSE.txt
cp 3rdparty/gtest/LICENSE %{buildroot}/usr/share/package-licenses/bpftrace/3rdparty_gtest_LICENSE
cp 3rdparty/gtest/googlemock/LICENSE %{buildroot}/usr/share/package-licenses/bpftrace/3rdparty_gtest_googlemock_LICENSE
cp 3rdparty/gtest/googlemock/scripts/generator/LICENSE %{buildroot}/usr/share/package-licenses/bpftrace/3rdparty_gtest_googlemock_scripts_generator_LICENSE
cp 3rdparty/gtest/googletest/LICENSE %{buildroot}/usr/share/package-licenses/bpftrace/3rdparty_gtest_googletest_LICENSE
cp LICENSE %{buildroot}/usr/share/package-licenses/bpftrace/LICENSE
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)
/usr/man/man8/bashreadline.8.gz
/usr/man/man8/biolatency.8.gz
/usr/man/man8/biosnoop.8.gz
/usr/man/man8/bitesize.8.gz
/usr/man/man8/bpftrace.8.gz
/usr/man/man8/capable.8.gz
/usr/man/man8/cpuwalk.8.gz
/usr/man/man8/dcsnoop.8.gz
/usr/man/man8/execsnoop.8.gz
/usr/man/man8/gethostlatency.8.gz
/usr/man/man8/killsnoop.8.gz
/usr/man/man8/loads.8.gz
/usr/man/man8/mdflush.8.gz
/usr/man/man8/oomkill.8.gz
/usr/man/man8/opensnoop.8.gz
/usr/man/man8/pidpersec.8.gz
/usr/man/man8/runqlat.8.gz
/usr/man/man8/runqlen.8.gz
/usr/man/man8/statsnoop.8.gz
/usr/man/man8/syncsnoop.8.gz
/usr/man/man8/syscount.8.gz
/usr/man/man8/vfscount.8.gz
/usr/man/man8/vfsstat.8.gz
/usr/man/man8/writeback.8.gz
/usr/man/man8/xfsdist.8.gz

%files bin
%defattr(-,root,root,-)
/usr/bin/bpftrace

%files data
%defattr(-,root,root,-)
/usr/share/bpftrace/tools/bashreadline.bt
/usr/share/bpftrace/tools/biolatency.bt
/usr/share/bpftrace/tools/biosnoop.bt
/usr/share/bpftrace/tools/bitesize.bt
/usr/share/bpftrace/tools/capable.bt
/usr/share/bpftrace/tools/cpuwalk.bt
/usr/share/bpftrace/tools/dcsnoop.bt
/usr/share/bpftrace/tools/execsnoop.bt
/usr/share/bpftrace/tools/gethostlatency.bt
/usr/share/bpftrace/tools/killsnoop.bt
/usr/share/bpftrace/tools/loads.bt
/usr/share/bpftrace/tools/mdflush.bt
/usr/share/bpftrace/tools/oomkill.bt
/usr/share/bpftrace/tools/opensnoop.bt
/usr/share/bpftrace/tools/pidpersec.bt
/usr/share/bpftrace/tools/runqlat.bt
/usr/share/bpftrace/tools/runqlen.bt
/usr/share/bpftrace/tools/statsnoop.bt
/usr/share/bpftrace/tools/syncsnoop.bt
/usr/share/bpftrace/tools/syscount.bt
/usr/share/bpftrace/tools/vfscount.bt
/usr/share/bpftrace/tools/vfsstat.bt
/usr/share/bpftrace/tools/writeback.bt
/usr/share/bpftrace/tools/xfsdist.bt

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/bpftrace/3rdparty_bcc_LICENSE.txt
/usr/share/package-licenses/bpftrace/3rdparty_gtest_LICENSE
/usr/share/package-licenses/bpftrace/3rdparty_gtest_googlemock_LICENSE
/usr/share/package-licenses/bpftrace/3rdparty_gtest_googlemock_scripts_generator_LICENSE
/usr/share/package-licenses/bpftrace/3rdparty_gtest_googletest_LICENSE
/usr/share/package-licenses/bpftrace/LICENSE
