#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v16
# autospec commit: 1bec16f
#
Name     : bpftrace
Version  : 0.21.2
Release  : 30
URL      : https://github.com/iovisor/bpftrace/archive/v0.21.2/bpftrace-0.21.2.tar.gz
Source0  : https://github.com/iovisor/bpftrace/archive/v0.21.2/bpftrace-0.21.2.tar.gz
Summary  : High-level tracing language for Linux eBPF
Group    : Development/Tools
License  : Apache-2.0
Requires: bpftrace-bin = %{version}-%{release}
Requires: bpftrace-data = %{version}-%{release}
Requires: bpftrace-license = %{version}-%{release}
Requires: bpftrace-man = %{version}-%{release}
BuildRequires : bcc-dev
BuildRequires : bison-dev
BuildRequires : buildreq-cmake
BuildRequires : cereal-dev
BuildRequires : flex
BuildRequires : flex-dev
BuildRequires : glibc-dev
BuildRequires : googletest-dev
BuildRequires : libbpf-dev
BuildRequires : libxml2-dev
BuildRequires : llvm-dev
BuildRequires : llvm-staticdev
BuildRequires : pkg-config
BuildRequires : pkgconfig(libelf)
BuildRequires : pkgconfig(libsystemd)
BuildRequires : zlib-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-Don-t-use-asciidoctor.patch

%description
# bpftrace
[![Build Status](https://github.com/bpftrace/bpftrace/workflows/CI/badge.svg?branch=master)](https://github.com/bpftrace/bpftrace/actions?query=workflow%3ACI+branch%3Amaster)
[![IRC#bpftrace](https://img.shields.io/badge/IRC-bpftrace-blue.svg)](https://webchat.oftc.net/?channels=bpftrace)
[![CodeQL](https://github.com/bpftrace/bpftrace/actions/workflows/codeql.yml/badge.svg)](https://github.com/bpftrace/bpftrace/actions/workflows/codeql.yml)

%package bin
Summary: bin components for the bpftrace package.
Group: Binaries
Requires: bpftrace-data = %{version}-%{release}
Requires: bpftrace-license = %{version}-%{release}

%description bin
bin components for the bpftrace package.


%package data
Summary: data components for the bpftrace package.
Group: Data

%description data
data components for the bpftrace package.


%package license
Summary: license components for the bpftrace package.
Group: Default

%description license
license components for the bpftrace package.


%package man
Summary: man components for the bpftrace package.
Group: Default

%description man
man components for the bpftrace package.


%prep
%setup -q -n bpftrace-0.21.2
cd %{_builddir}/bpftrace-0.21.2
%patch -P 1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1721407591
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake .. -DBUILD_TESTING=OFF \
-DBUILD_SHARED_LIBS=OFF \
-DCMAKE_BUILD_TYPE=Release \
-DUSE_SYSTEM_BPF_BCC=ON  -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd

%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1721407591
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/bpftrace
cp %{_builddir}/bpftrace-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/bpftrace/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
export GOAMD64=v2
GOAMD64=v2
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/bpftrace
/usr/bin/bpftrace-aotrt

%files data
%defattr(-,root,root,-)
/usr/share/bpftrace/tools/bashreadline.bt
/usr/share/bpftrace/tools/biolatency-kp.bt
/usr/share/bpftrace/tools/biolatency.bt
/usr/share/bpftrace/tools/biosnoop.bt
/usr/share/bpftrace/tools/biostacks.bt
/usr/share/bpftrace/tools/bitesize.bt
/usr/share/bpftrace/tools/capable.bt
/usr/share/bpftrace/tools/cpuwalk.bt
/usr/share/bpftrace/tools/dcsnoop.bt
/usr/share/bpftrace/tools/doc/bashreadline_example.txt
/usr/share/bpftrace/tools/doc/biolatency_example.txt
/usr/share/bpftrace/tools/doc/biosnoop_example.txt
/usr/share/bpftrace/tools/doc/biostacks_example.txt
/usr/share/bpftrace/tools/doc/bitesize_example.txt
/usr/share/bpftrace/tools/doc/capable_example.txt
/usr/share/bpftrace/tools/doc/cpuwalk_example.txt
/usr/share/bpftrace/tools/doc/dcsnoop_example.txt
/usr/share/bpftrace/tools/doc/execsnoop_example.txt
/usr/share/bpftrace/tools/doc/gethostlatency_example.txt
/usr/share/bpftrace/tools/doc/killsnoop_example.txt
/usr/share/bpftrace/tools/doc/loads_example.txt
/usr/share/bpftrace/tools/doc/mdflush_example.txt
/usr/share/bpftrace/tools/doc/naptime_example.txt
/usr/share/bpftrace/tools/doc/oomkill_example.txt
/usr/share/bpftrace/tools/doc/opensnoop_example.txt
/usr/share/bpftrace/tools/doc/pidpersec_example.txt
/usr/share/bpftrace/tools/doc/runqlat_example.txt
/usr/share/bpftrace/tools/doc/runqlen_example.txt
/usr/share/bpftrace/tools/doc/setuids_example.txt
/usr/share/bpftrace/tools/doc/ssllatency_example.txt
/usr/share/bpftrace/tools/doc/sslsnoop_example.txt
/usr/share/bpftrace/tools/doc/statsnoop_example.txt
/usr/share/bpftrace/tools/doc/swapin_example.txt
/usr/share/bpftrace/tools/doc/syncsnoop_example.txt
/usr/share/bpftrace/tools/doc/syscount_example.txt
/usr/share/bpftrace/tools/doc/tcpaccept_example.txt
/usr/share/bpftrace/tools/doc/tcpconnect_example.txt
/usr/share/bpftrace/tools/doc/tcpdrop_example.txt
/usr/share/bpftrace/tools/doc/tcplife_example.txt
/usr/share/bpftrace/tools/doc/tcpretrans_example.txt
/usr/share/bpftrace/tools/doc/tcpsynbl_example.txt
/usr/share/bpftrace/tools/doc/threadsnoop_example.txt
/usr/share/bpftrace/tools/doc/undump_example.txt
/usr/share/bpftrace/tools/doc/vfscount_example.txt
/usr/share/bpftrace/tools/doc/vfsstat_example.txt
/usr/share/bpftrace/tools/doc/writeback_example.txt
/usr/share/bpftrace/tools/doc/xfsdist_example.txt
/usr/share/bpftrace/tools/execsnoop.bt
/usr/share/bpftrace/tools/gethostlatency.bt
/usr/share/bpftrace/tools/killsnoop.bt
/usr/share/bpftrace/tools/loads.bt
/usr/share/bpftrace/tools/mdflush.bt
/usr/share/bpftrace/tools/naptime.bt
/usr/share/bpftrace/tools/old/biosnoop.bt
/usr/share/bpftrace/tools/old/mdflush.bt
/usr/share/bpftrace/tools/old/tcpdrop.bt
/usr/share/bpftrace/tools/oomkill.bt
/usr/share/bpftrace/tools/opensnoop.bt
/usr/share/bpftrace/tools/pidpersec.bt
/usr/share/bpftrace/tools/runqlat.bt
/usr/share/bpftrace/tools/runqlen.bt
/usr/share/bpftrace/tools/setuids.bt
/usr/share/bpftrace/tools/ssllatency.bt
/usr/share/bpftrace/tools/sslsnoop.bt
/usr/share/bpftrace/tools/statsnoop.bt
/usr/share/bpftrace/tools/swapin.bt
/usr/share/bpftrace/tools/syncsnoop.bt
/usr/share/bpftrace/tools/syscount.bt
/usr/share/bpftrace/tools/tcpaccept.bt
/usr/share/bpftrace/tools/tcpconnect.bt
/usr/share/bpftrace/tools/tcpdrop.bt
/usr/share/bpftrace/tools/tcplife.bt
/usr/share/bpftrace/tools/tcpretrans.bt
/usr/share/bpftrace/tools/tcpsynbl.bt
/usr/share/bpftrace/tools/threadsnoop.bt
/usr/share/bpftrace/tools/undump.bt
/usr/share/bpftrace/tools/vfscount.bt
/usr/share/bpftrace/tools/vfsstat.bt
/usr/share/bpftrace/tools/writeback.bt
/usr/share/bpftrace/tools/xfsdist.bt

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/bpftrace/2b8b815229aa8a61e483fb4ba0588b8b6c491890

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man8/bashreadline.bt.8.gz
/usr/share/man/man8/biolatency.bt.8.gz
/usr/share/man/man8/biosnoop.bt.8.gz
/usr/share/man/man8/biostacks.bt.8.gz
/usr/share/man/man8/bitesize.bt.8.gz
/usr/share/man/man8/capable.bt.8.gz
/usr/share/man/man8/cpuwalk.bt.8.gz
/usr/share/man/man8/dcsnoop.bt.8.gz
/usr/share/man/man8/execsnoop.bt.8.gz
/usr/share/man/man8/gethostlatency.bt.8.gz
/usr/share/man/man8/killsnoop.bt.8.gz
/usr/share/man/man8/loads.bt.8.gz
/usr/share/man/man8/mdflush.bt.8.gz
/usr/share/man/man8/naptime.bt.8.gz
/usr/share/man/man8/oomkill.bt.8.gz
/usr/share/man/man8/opensnoop.bt.8.gz
/usr/share/man/man8/pidpersec.bt.8.gz
/usr/share/man/man8/runqlat.bt.8.gz
/usr/share/man/man8/runqlen.bt.8.gz
/usr/share/man/man8/setuids.bt.8.gz
/usr/share/man/man8/ssllatency.bt.8.gz
/usr/share/man/man8/sslsnoop.bt.8.gz
/usr/share/man/man8/statsnoop.bt.8.gz
/usr/share/man/man8/swapin.bt.8.gz
/usr/share/man/man8/syncsnoop.bt.8.gz
/usr/share/man/man8/syscount.bt.8.gz
/usr/share/man/man8/tcpaccept.bt.8.gz
/usr/share/man/man8/tcpconnect.bt.8.gz
/usr/share/man/man8/tcpdrop.bt.8.gz
/usr/share/man/man8/tcplife.bt.8.gz
/usr/share/man/man8/tcpretrans.bt.8.gz
/usr/share/man/man8/tcpsynbl.bt.8.gz
/usr/share/man/man8/threadsnoop.bt.8.gz
/usr/share/man/man8/undump.bt.8.gz
/usr/share/man/man8/vfscount.bt.8.gz
/usr/share/man/man8/vfsstat.bt.8.gz
/usr/share/man/man8/writeback.bt.8.gz
/usr/share/man/man8/xfsdist.bt.8.gz
